### PR TITLE
Add Your Suggestions

### PR DESCRIPTION
**Pull request by tommyp6**
@tjguk I added some of your suggestions like : 

- Simplify the read function.
- Add More specific Errors + More Exceptions.
- Update the docstrings.
- Some other things.

### CODE REVIEW

**Review by tjguk — COMMENTED** [review]
Much better with the docstrings.

I'm not 100% sure what you're doing with the counter (c) despite your explanation. But I think that what you're effectively doing is simulating a for-else situation. Experiment with something like the following:

```
names = ['Alice', 'Bob', 'Charlie', 'Bob']
look_for = input("Name: ")
for name in names:
    if name == look_for:
        print("Found:", name)
        break
else:
    print(name, "not found")
```

Note that the `else` is paired with the `for`, not with the if`

**Comment by tommyp6** [comment]
The counter is used for if there is more than one option. Because If not I have two options : 

1. exit the code with one result or Not Found.
2. Add the counter so if there are more than one result don't say Not Found for every line that does not contain the name : 
```python
c = 0
	
with open("db.txt","r") as db:
		
	for lines in db: 

		name, age, color = lines.split()
		
		if name == f_name:
			
			c += 1
					
			print("\n[+] Found :\n\n* Name : " + name,"\n* Age : " + age + "\n* Favourite color : " + color + "\n")
						
		
		if not name == f_name:
			
			if c <= 1:
				pass
				
			else:
				print("\n[*] Not Found ")
				exit()

```

with the `for` For every line there is a name not found it will give for e.g. three times Not Found. But with the counter I can check for more options without Not Found.
the other option is kill the code with just one output.

**Comment by tjguk** [comment]
Ah. I understand. So the counter isn't really a counter; it's a flag which says "I found at least one". In that case, I'd just switch to a boolean, eg

```python
names = ['Alice', 'Bob', 'Charlie', 'Bob']
none_found = True
look_for = input("Look for: ")

for name in names:
  if name == look_for:
    none_found = False
    print("Found:", name)

if none_found:
  print("Could not find", name)

```

The key difference is that the variable `none_found` makes it clearer what its purpose is in the code. If you use what is in effect a counter, it will work (as you've shown) but it makes the reader assume that you're interested in the number of matches rather than simply the fact of a match.

(Of course if you *are* interested in the number, eg so you can say at the end: `print("%d matches found" % c)` then by all means use a counter :)

**Comment by tjguk** [comment]
@TommyPujol06 BTW thanks for showing me how to force the syntax highlighting to Python for an embedded code block. I didn't know you could do that :)

**Pull request merged**
